version: '2.1'
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    links:
      - oauth2_proxy
      - kibana
    volumes:
      - ./proxy/config/nginx.conf:/etc/nginx/nginx.conf
      - ./proxy/config/server.crt:/etc/ssl/server.crt
      - ./proxy/config/server.key:/etc/ssl/server.key
    networks:
      - elknet

  oauth2_proxy:
    image: oauth2_proxy:rft
    build:
      context: proxy
    container_name: oauth2_proxy
    environment:
    - "OAUTH2_PROXY_CLIENT_ID="
    - "OAUTH2_PROXY_CLIENT_SECRET="
    - "OAUTH2_PROXY_COOKIE_NAME=_oauth2_proxy"
    - "OAUTH2_PROXY_COOKIE_SECRET="
    - "OAUTH2_PROXY_COOKIE_DOMAIN=localhost"
    - "OAUTH2_PROXY_COOKIE_EXPIRE=168h"
    - "OAUTH2_PROXY_COOKIE_REFRESH=1h"
    links:
      - kibana
    volumes:
      - ./proxy/config/oauth2.cfg:/go/src/app/oauth2.cfg
    networks:
      - elknet